### ISSUE TITLE
是否支持本地私有部署的大模型 funciton call 能力

### ISSUE THREAD

**Issue by shaojool** [oldmanpushcart/dashscope4j#14]

**Comment by oldmanpushcart** [comment]
我没部署过通义千问的本地私有部署大模型，所以没有办法给你确定性的答案。主要是我没有动力去做这样的事。
理论上是支持的，但需要做一些修改和适配。比如我知道的baseUrl的修改就没放出来，当前还是写死在了代码中。

代码是开源的，你如果有需要可以clone去修改，记得pull-request回来哦，我会很欢迎这样做。
