### ISSUE TITLE
Java8跑不了

### ISSUE THREAD

**Issue by al1020119** [oldmanpushcart/dashscope4j#2]
错误的类文件: /Users/edy/Service/Mavens/apache-maven-3.8.4/repository/io/github/oldmanpushcart/dashscope4j/1.2.1/dashscope4j-1.2.1.jar!/io/github/oldmanpushcart/dashscope4j/DashScopeClient.class
    类文件具有错误的版本 61.0, 应为 52.0
    请删除该文件或确保该文件位于正确的类路径子目录中。

**Comment by oldmanpushcart** [comment]
Hi 你好

`dashscope4j`是基于JDK17进行设计的，所以不支持JDK8。

这里容许我稍微做一下不支持JDK8这个决定的原因

1. JAR包依赖考虑；Java在JDK11的时候才自带了HttpClient，为了降低自身JAR包冲突的概率，所以我挑选了JDK自带的HttpClient来完成这个项目
2. LTS考虑；当前JDK的三个生命周期中的LTS版本：11、17和21，所有的软件库在设计的时候必须基于LTS版本进行设计。
3. `record`语法糖；JDK14引入的record语法太适合做DTO的事情了，让我爱不释手。

综上三个原因，最终让我选择了JDK17来构建这个项目。其他类似SpringBoot3.0也是基于JDK17来完成，估计他们也有自己类似的原因吧。

当然我也可以修改项目代码支持JDK11（放弃`record`语法糖的诱惑），前提是有其他人需要这样做。

**Comment by oldmanpushcart** [comment]
Hi 你好

`dashscope4j`是基于JDK17进行设计的，所以不支持JDK8。

这里容许我稍稍解释下不支持JDK8这个决定的原因

1. JAR包依赖考虑；Java在JDK11的时候才自带了HttpClient，为了降低自身JAR包冲突的概率，所以我挑选了JDK自带的HttpClient来完成这个项目
2. LTS考虑；当前JDK的三个生命周期中的LTS版本：11、17和21，所有的软件库在设计的时候必须基于LTS版本进行设计。
3. `record`语法糖；JDK14引入的record语法太适合做DTO的事情了，让我爱不释手。

综上三个原因，最终让我选择了JDK17来构建这个项目。其他类似SpringBoot3.0也是基于JDK17来完成，估计他们也有自己类似的原因吧。

当然我也可以修改项目代码支持JDK11（放弃`record`语法糖的诱惑），前提是有其他人需要这样做。
